### ISSUE TITLE
EBUSY: resource busy or locked, unlink 

### ISSUE THREAD

**Issue by jamiejackson** [ICFI/eagle#25]
Getting problems in the Jenkins jobs. Clues:

* The `/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  * Is there something wrong with this package?
* '/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/chokidar/node_modules/fsevents/node_modules/chownr/**.nfs**9cb9fbc2cc720ede00000dd6'
  * Is there a problem with NFS (EFS)?

```
...
npm info lifecycle got@7.1.0~postinstall: got@7.1.0
npm info lifecycle tunnel-agent@0.6.0~postinstall: tunnel-agent@0.6.0
npm info lifecycle caw@2.0.1~postinstall: caw@2.0.1
npm info lifecycle unbzip2-stream@1.2.5~postinstall: unbzip2-stream@1.2.5
npm info lifecycle decompress-tarbz2@4.1.1~postinstall: decompress-tarbz2@4.1.1
npm info lifecycle decompress@4.2.0~postinstall: decompress@4.2.0
npm info lifecycle download@6.2.5~postinstall: download@6.2.5
npm info lifecycle bin-build@3.0.0~postinstall: bin-build@3.0.0
npm info lifecycle pngquant-bin@4.0.0~postinstall: pngquant-bin@4.0.0

> pngquant-bin@4.0.0 postinstall /var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm verb lifecycle pngquant-bin@4.0.0~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle pngquant-bin@4.0.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin/node_modules/.bin:/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/.bin:/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle pngquant-bin@4.0.0~postinstall: CWD: /var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin
npm info lifecycle pngquant-bin@4.0.0~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 8304ms
npm verb unlock done using /var/jenkins_home/.npm/_locks/staging-1f5e59b468aa1814.lock for /var/jenkins_home/workspace/eagle_jj/eagle/node_modules/.staging
npm WARN rollback Rolling back balanced-match@1.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/chokidar/node_modules/fsevents/node_modules/balanced-match/.nfsb72ddc94d067600e00000dd3'
npm WARN rollback Rolling back abbrev@1.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/chokidar/node_modules/fsevents/node_modules/abbrev/.nfsed818421624776ac00000dd2'
npm WARN rollback Rolling back aproba@1.2.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/chokidar/node_modules/fsevents/node_modules/aproba/.nfs48bc08b1bd4191c800000dd5'
npm WARN rollback Rolling back chownr@1.0.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/chokidar/node_modules/fsevents/node_modules/chownr/.nfs9cb9fbc2cc720ede00000dd6'
npm WARN rollback Rolling back console-control-strings@1.1.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink 
...
```

**Comment by jamiejackson** [comment]
> Is there a problem with NFS (EFS)?

https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=123962105

So those `.nfsXXXXX` files are generated when one nfs client deletes a file that another has open. I'm not sure what contention there might be yet.

**Comment by jamiejackson** [comment]
> * The `/var/jenkins_home/workspace/eagle_jj/eagle/node_modules/image-webpack-loader/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
>    * Is there something wrong with this package?

Spinning this off to a new ticket.
